import type { GlassItem, FittingRole } from '@/types';
import { db } from '@/lib/storage';

/**
 * Complete Architectural Glass Hardware Master Catalog
 * Exhaustive 85+ item inventory database spanning DORMA (dormakaba), Ozone India,
 * Icon Architectural Hardware, Häfele, Hardwyn, Enox, and CRL.
 */
export const MASTER_HARDWARE_CATALOG: GlassItem[] = [
    // =========================================================================
    // 1. DORMA / dormakaba (Floor Springs, Patch Fittings, Sliding, Hinges)
    // =========================================================================
    {
        id: 'cat_dorma_bts80',
        name: 'DORMA BTS 80 Heavy-Duty Floor Spring (300kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'DORMA',
        model: 'BTS 80',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 0 },
        rate: 12500,
        rateUnit: 'nos',
        purchaseRate: 9200,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_bts84',
        name: 'DORMA BTS 84 Double Action Floor Spring (100kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'DORMA',
        model: 'BTS 84',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 6200,
        rateUnit: 'nos',
        purchaseRate: 4400,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_bts75v',
        name: 'DORMA BTS 75V Variable Spring Strength Floor Spring (150kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'DORMA',
        model: 'BTS 75V',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 5 },
        rate: 8400,
        rateUnit: 'nos',
        purchaseRate: 6100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_bts65',
        name: 'DORMA BTS 65 Compact Floor Spring (80kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'DORMA',
        model: 'BTS 65',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 0 },
        rate: 4800,
        rateUnit: 'nos',
        purchaseRate: 3500,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_rts85',
        name: 'DORMA RTS 85 Transom Concealed Door Closer',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'DORMA',
        model: 'RTS 85',
        unit: 'nos',
        stock: 12,
        warehouseStock: { 'Warehouse A': 12, 'Warehouse B': 0 },
        rate: 9800,
        rateUnit: 'nos',
        purchaseRate: 7100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_pt10',
        name: 'DORMA PT 10 Universal Bottom Patch Fitting',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 10',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1450,
        rateUnit: 'nos',
        purchaseRate: 1020,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt20',
        name: 'DORMA PT 20 Universal Top Patch Fitting',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 20',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1450,
        rateUnit: 'nos',
        purchaseRate: 1020,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt22',
        name: 'DORMA PT 22 Overpanel Patch Fitting with Fin Support',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 22',
        unit: 'nos',
        stock: 18,
        warehouseStock: { 'Warehouse A': 18, 'Warehouse B': 0 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1580,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt24',
        name: 'DORMA PT 24 Overpanel Pivot Patch with Door Stop',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 24',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 0 },
        rate: 1950,
        rateUnit: 'nos',
        purchaseRate: 1400,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt30',
        name: 'DORMA PT 30 Overpanel Transom Patch with Pivot',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 30',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 1850,
        rateUnit: 'nos',
        purchaseRate: 1320,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt40',
        name: 'DORMA PT 40 Side Fin Support Junction Patch',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 40',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 0 },
        rate: 2450,
        rateUnit: 'nos',
        purchaseRate: 1780,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt41',
        name: 'DORMA PT 41 4-Way Overpanel & Side Fin Junction Patch',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 41',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 0 },
        rate: 3100,
        rateUnit: 'nos',
        purchaseRate: 2250,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_dorma_pt60',
        name: 'DORMA PT 60 Connector Patch for Overpanel & Side Panel',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 60',
        unit: 'nos',
        stock: 22,
        warehouseStock: { 'Warehouse A': 22, 'Warehouse B': 0 },
        rate: 1750,
        rateUnit: 'nos',
        purchaseRate: 1250,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_pt70',
        name: 'DORMA PT 70 Overpanel Connector Patch with Stop Insert',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'PT 70',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 0 },
        rate: 1900,
        rateUnit: 'nos',
        purchaseRate: 1380,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_us10',
        name: 'DORMA US 10 Corner Deadbolt Patch Lock (Euro Cylinder)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'DORMA',
        model: 'US 10',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 10 },
        rate: 2800,
        rateUnit: 'nos',
        purchaseRate: 2050,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_us20',
        name: 'DORMA US 20 Center Meeting Stile Patch Lock',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'DORMA',
        model: 'US 20',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 0 },
        rate: 3200,
        rateUnit: 'nos',
        purchaseRate: 2350,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_arcos_pt10',
        name: 'DORMA Arcos PT 10 Architectural Curved Bottom Patch',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'Arcos PT 10',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 0 },
        rate: 2600,
        rateUnit: 'nos',
        purchaseRate: 1850,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_arcos_pt20',
        name: 'DORMA Arcos PT 20 Architectural Curved Top Patch',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'Arcos PT 20',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 0 },
        rate: 2600,
        rateUnit: 'nos',
        purchaseRate: 1850,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_agile50',
        name: 'DORMA Agile 50 Concealed Sliding Glass Door Kit',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'DORMA',
        model: 'Agile 50',
        unit: 'nos',
        stock: 10,
        warehouseStock: { 'Warehouse A': 10, 'Warehouse B': 0 },
        rate: 11500,
        rateUnit: 'nos',
        purchaseRate: 8500,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_agile150',
        name: 'DORMA Agile 150 Heavy-Duty Sliding Track System (150kg)',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'DORMA',
        model: 'Agile 150',
        unit: 'nos',
        stock: 12,
        warehouseStock: { 'Warehouse A': 10, 'Warehouse B': 2 },
        rate: 16500,
        rateUnit: 'nos',
        purchaseRate: 12200,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_rs120',
        name: 'DORMA RS 120 Roller Sliding Glass Door Track Assembly',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'DORMA',
        model: 'RS 120',
        unit: 'nos',
        stock: 14,
        warehouseStock: { 'Warehouse A': 14, 'Warehouse B': 0 },
        rate: 14800,
        rateUnit: 'nos',
        purchaseRate: 10800,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_manet_slider',
        name: 'DORMA Manet Single-Point Stainless Sliding Door Track',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'DORMA',
        model: 'Manet Slider',
        unit: 'nos',
        stock: 8,
        warehouseStock: { 'Warehouse A': 8, 'Warehouse B': 0 },
        rate: 24500,
        rateUnit: 'nos',
        purchaseRate: 18200,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 4,
        cutsRequired: 0
    },
    {
        id: 'cat_dorma_tensor_w2g',
        name: 'DORMA Tensor Wall-to-Glass Self-Closing Double Action Hinge',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'DORMA',
        model: 'Tensor Wall Hinge',
        unit: 'nos',
        stock: 16,
        warehouseStock: { 'Warehouse A': 16, 'Warehouse B': 0 },
        rate: 6800,
        rateUnit: 'nos',
        purchaseRate: 4900,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_dorma_tensor_g2g',
        name: 'DORMA Tensor Glass-to-Glass 180° Self-Closing Hinge',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'DORMA',
        model: 'Tensor Glass Hinge',
        unit: 'nos',
        stock: 14,
        warehouseStock: { 'Warehouse A': 14, 'Warehouse B': 0 },
        rate: 7400,
        rateUnit: 'nos',
        purchaseRate: 5400,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_dorma_beyond_pivot',
        name: 'DORMA Beyond Anti-Finger Trap Full Pivot Door Fitting Kit',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'DORMA',
        model: 'Beyond Pivot',
        unit: 'nos',
        stock: 6,
        warehouseStock: { 'Warehouse A': 6, 'Warehouse B': 0 },
        rate: 18500,
        rateUnit: 'nos',
        purchaseRate: 13500,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 0,
        cutsRequired: 0
    },

    // =========================================================================
    // 2. OZONE INDIA (Floor Springs, Patches, Showers, Spiders, Spigots)
    // =========================================================================
    {
        id: 'cat_ozone_fs84',
        name: 'Ozone Double Action Floor Spring OZ-FS-84 (100kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Ozone',
        model: 'OZ-FS-84',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 15 },
        rate: 4500,
        rateUnit: 'nos',
        purchaseRate: 3150,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_fs75v',
        name: 'Ozone Variable Power Floor Spring OZ-FS-75V (150kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Ozone',
        model: 'OZ-FS-75V',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 6400,
        rateUnit: 'nos',
        purchaseRate: 4600,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_fs90',
        name: 'Ozone Heavy Duty Floor Spring OZ-FS-90 (300kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Ozone',
        model: 'OZ-FS-90',
        unit: 'nos',
        stock: 12,
        warehouseStock: { 'Warehouse A': 12, 'Warehouse B': 0 },
        rate: 9800,
        rateUnit: 'nos',
        purchaseRate: 7200,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_hdc100',
        name: 'Ozone Hydraulic Bottom Patch Door Closer OZ-HDC-100 (No Floor Dig)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Ozone',
        model: 'OZ-HDC-100',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 18, 'Warehouse B': 7 },
        rate: 7500,
        rateUnit: 'nos',
        purchaseRate: 5300,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf10',
        name: 'Ozone Bottom Patch Fitting OZ-PF-10 (65mm Setback)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-10',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 980,
        rateUnit: 'nos',
        purchaseRate: 680,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf20',
        name: 'Ozone Top Patch Fitting OZ-PF-20 (55mm Setback)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-20',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 980,
        rateUnit: 'nos',
        purchaseRate: 680,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf30',
        name: 'Ozone Overpanel Transom Patch OZ-PF-30 with Pivot',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-30',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 1350,
        rateUnit: 'nos',
        purchaseRate: 950,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf40',
        name: 'Ozone Side Fin Connector Patch OZ-PF-40',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-40',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 0 },
        rate: 1750,
        rateUnit: 'nos',
        purchaseRate: 1240,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf50',
        name: 'Ozone Wall-to-Glass Overpanel Connector OZ-PF-50',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-50',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 0 },
        rate: 1550,
        rateUnit: 'nos',
        purchaseRate: 1100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf60',
        name: 'Ozone 4-Way Overpanel & Fin Connector OZ-PF-60',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Ozone',
        model: 'OZ-PF-60',
        unit: 'nos',
        stock: 18,
        warehouseStock: { 'Warehouse A': 18, 'Warehouse B': 0 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1550,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_ozone_pf100',
        name: 'Ozone Corner Deadbolt Lock Patch OZ-PF-100 (Euro Cylinder)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PF-100',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1580,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_pf200',
        name: 'Ozone Center Double-Door Lock Patch OZ-PF-200',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PF-200',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 5 },
        rate: 2450,
        rateUnit: 'nos',
        purchaseRate: 1750,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_oz_wh_180',
        name: 'Ozone Wall-to-Glass 90° Shower Hinge (OZ-WH-180)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Ozone',
        model: 'OZ-WH-180',
        unit: 'nos',
        stock: 80,
        warehouseStock: { 'Warehouse A': 50, 'Warehouse B': 30 },
        rate: 1450,
        rateUnit: 'nos',
        purchaseRate: 1020,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_ozone_oz_g2g_180',
        name: 'Ozone Inline 180° Glass-to-Glass Shower Hinge (OZ-G2G-180)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Ozone',
        model: 'OZ-G2G-180',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 20 },
        rate: 1850,
        rateUnit: 'nos',
        purchaseRate: 1320,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_ozone_oz_g2g_90',
        name: 'Ozone Corner 90° Glass-to-Glass Shower Hinge (OZ-G2G-90)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Ozone',
        model: 'OZ-G2G-90',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 1950,
        rateUnit: 'nos',
        purchaseRate: 1380,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_ozone_oz_g2g_135',
        name: 'Ozone Neo-Angle 135° Shower Enclosure Hinge (OZ-G2G-135)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Ozone',
        model: 'OZ-G2G-135',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 2050,
        rateUnit: 'nos',
        purchaseRate: 1450,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_ozone_oz_sh_sl01',
        name: 'Ozone Soft-Close Roller Shower Sliding Door Kit (OZ-SH-SL01)',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'Ozone',
        model: 'OZ-SH-SL01',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 10, 'Warehouse B': 5 },
        rate: 8500,
        rateUnit: 'nos',
        purchaseRate: 6100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sp_101',
        name: 'Ozone 1-Way Structural Glass Spider Fitting OZ-SP-101',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-SP-101',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 10 },
        rate: 1650,
        rateUnit: 'nos',
        purchaseRate: 1150,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sp_102',
        name: 'Ozone 2-Way Inline (180°) Structural Spider OZ-SP-102',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-SP-102',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 2450,
        rateUnit: 'nos',
        purchaseRate: 1750,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sp_102l',
        name: 'Ozone 2-Way Corner (90°) / Fin Spider Fitting OZ-SP-102L',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-SP-102L',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 2650,
        rateUnit: 'nos',
        purchaseRate: 1880,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sp_103',
        name: 'Ozone 3-Way Structural Spider Fitting OZ-SP-103',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-SP-103',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 0 },
        rate: 3400,
        rateUnit: 'nos',
        purchaseRate: 2400,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 3,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sp_104',
        name: 'Ozone 4-Way Complete Intersection Spider Fitting OZ-SP-104',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-SP-104',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 4200,
        rateUnit: 'nos',
        purchaseRate: 3050,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 4,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_routel_m16',
        name: 'Ozone Articulated Countersunk M16 Routel Bolt for Spiders',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Ozone',
        model: 'OZ-Routel-M16',
        unit: 'nos',
        stock: 150,
        warehouseStock: { 'Warehouse A': 100, 'Warehouse B': 50 },
        rate: 650,
        rateUnit: 'nos',
        purchaseRate: 450,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sr_2205',
        name: 'Ozone Duplex 2205 Grade Stainless Core-Drill Spigot OZ-SR-2205',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'Ozone',
        model: 'OZ-SR-2205',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 2850,
        rateUnit: 'nos',
        purchaseRate: 2050,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'spigot',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_sr_102',
        name: 'Ozone Surface-Mount Base-Plate Spigot OZ-SR-102 (No Drilling)',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'Ozone',
        model: 'OZ-SR-102',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 2600,
        rateUnit: 'nos',
        purchaseRate: 1850,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'spigot',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_ch_10',
        name: 'Ozone Heavy-Duty Continuous Aluminum Balustrade Channel (Per Meter)',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'Ozone',
        model: 'OZ-CH-10',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 0 },
        rate: 3400,
        rateUnit: 'nos',
        purchaseRate: 2450,
        purchaseRateUnit: 'nos',
        hsnCode: '76109010',
        fittingRole: 'spigot',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_ph01_300',
        name: 'Ozone Tubular Stainless Steel D-Pull Handle (300mm CTC)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PH-01-300',
        unit: 'nos',
        stock: 65,
        warehouseStock: { 'Warehouse A': 45, 'Warehouse B': 20 },
        rate: 950,
        rateUnit: 'nos',
        purchaseRate: 650,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'handle',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_ph01_450',
        name: 'Ozone Tubular Stainless Steel D-Pull Handle (450mm CTC)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PH-01-450',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1250,
        rateUnit: 'nos',
        purchaseRate: 880,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'handle',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_ph10_1200',
        name: 'Ozone H-Type Ladder Pull Handle with Key Lock (1200mm)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PH-10-1200',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 4200,
        rateUnit: 'nos',
        purchaseRate: 3050,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'handle',
        holesRequired: 3,
        cutsRequired: 0
    },
    {
        id: 'cat_ozone_ph10_1500',
        name: 'Ozone H-Type Ladder Pull Handle with Key Lock (1500mm)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Ozone',
        model: 'OZ-PH-10-1500',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 5 },
        rate: 5100,
        rateUnit: 'nos',
        purchaseRate: 3700,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'handle',
        holesRequired: 3,
        cutsRequired: 0
    },

    // =========================================================================
    // 3. ICON ARCHITECTURAL HARDWARE (Complete Architectural Catalog)
    // =========================================================================
    {
        id: 'cat_icon_fs84',
        name: 'Icon Double Action Glass Door Floor Spring (IC-FS-84)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Icon',
        model: 'IC-FS-84',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 15 },
        rate: 4200,
        rateUnit: 'nos',
        purchaseRate: 2900,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_fs75',
        name: 'Icon Heavy Duty Universal Floor Spring (IC-FS-75)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Icon',
        model: 'IC-FS-75',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 5800,
        rateUnit: 'nos',
        purchaseRate: 4100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_hym01',
        name: 'Icon Hydraulic Bottom Patch Door Closer (IC-HYM-01)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Icon',
        model: 'IC-HYM-01',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 5 },
        rate: 6800,
        rateUnit: 'nos',
        purchaseRate: 4900,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_pf10',
        name: 'Icon Universal Bottom Patch Fitting (IC-PF-10)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Icon',
        model: 'IC-PF-10',
        unit: 'nos',
        stock: 70,
        warehouseStock: { 'Warehouse A': 45, 'Warehouse B': 25 },
        rate: 890,
        rateUnit: 'nos',
        purchaseRate: 620,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_pf20',
        name: 'Icon Universal Top Patch Fitting (IC-PF-20)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Icon',
        model: 'IC-PF-20',
        unit: 'nos',
        stock: 70,
        warehouseStock: { 'Warehouse A': 45, 'Warehouse B': 25 },
        rate: 890,
        rateUnit: 'nos',
        purchaseRate: 620,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_pf30',
        name: 'Icon Overpanel Transom Pivot Patch (IC-PF-30)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Icon',
        model: 'IC-PF-30',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 1250,
        rateUnit: 'nos',
        purchaseRate: 880,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_pf40',
        name: 'Icon Side Fin Junction Support Patch (IC-PF-40)',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Icon',
        model: 'IC-PF-40',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 1650,
        rateUnit: 'nos',
        purchaseRate: 1150,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_us10',
        name: 'Icon Bottom Corner Deadbolt Lock Patch (IC-US-10)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Icon',
        model: 'IC-US-10',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1950,
        rateUnit: 'nos',
        purchaseRate: 1400,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_us20',
        name: 'Icon Central Meeting Stile Lock Fitting (IC-US-20)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Icon',
        model: 'IC-US-20',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1580,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_sh90',
        name: 'Icon Wall-to-Glass Solid Brass Shower Hinge (IC-SH-90)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Icon',
        model: 'IC-SH-90',
        unit: 'nos',
        stock: 80,
        warehouseStock: { 'Warehouse A': 50, 'Warehouse B': 30 },
        rate: 1350,
        rateUnit: 'nos',
        purchaseRate: 950,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_icon_sh180',
        name: 'Icon Inline 180° Glass-to-Glass Shower Hinge (IC-SH-180)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Icon',
        model: 'IC-SH-180',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 1750,
        rateUnit: 'nos',
        purchaseRate: 1250,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_icon_sh135',
        name: 'Icon 135° Neo-Angle Shower Hinge (IC-SH-135)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Icon',
        model: 'IC-SH-135',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 1850,
        rateUnit: 'nos',
        purchaseRate: 1320,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_icon_cl01',
        name: 'Icon Square Solid Brass Wall Mounting Clamp (IC-CL-01)',
        category: 'hardware',
        type: 'Clamps & Connectors',
        make: 'Icon',
        model: 'IC-CL-01',
        unit: 'nos',
        stock: 120,
        warehouseStock: { 'Warehouse A': 80, 'Warehouse B': 40 },
        rate: 450,
        rateUnit: 'nos',
        purchaseRate: 310,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'clamp',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_cl02',
        name: 'Icon D-Shape Partition Wall Clamp (IC-CL-02)',
        category: 'hardware',
        type: 'Clamps & Connectors',
        make: 'Icon',
        model: 'IC-CL-02',
        unit: 'nos',
        stock: 100,
        warehouseStock: { 'Warehouse A': 60, 'Warehouse B': 40 },
        rate: 480,
        rateUnit: 'nos',
        purchaseRate: 330,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'clamp',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_sp1',
        name: 'Icon 1-Way Fin Spider Fitting (IC-SP-1)',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Icon',
        model: 'IC-SP-1',
        unit: 'nos',
        stock: 40,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 15 },
        rate: 1450,
        rateUnit: 'nos',
        purchaseRate: 1020,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_sp2',
        name: 'Icon 2-Way Inline Structural Spider (IC-SP-2)',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Icon',
        model: 'IC-SP-2',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1550,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_sp4',
        name: 'Icon 4-Way Curtain Wall Intersection Spider (IC-SP-4)',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'Icon',
        model: 'IC-SP-4',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 3800,
        rateUnit: 'nos',
        purchaseRate: 2750,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 4,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_spg01',
        name: 'Icon Core-Drill Balustrade Stainless Spigot (IC-SPG-01)',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'Icon',
        model: 'IC-SPG-01',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 2450,
        rateUnit: 'nos',
        purchaseRate: 1750,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'spigot',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_spg02',
        name: 'Icon Surface Flange Mount Spigot (IC-SPG-02)',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'Icon',
        model: 'IC-SPG-02',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 2350,
        rateUnit: 'nos',
        purchaseRate: 1680,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'spigot',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_sl100',
        name: 'Icon Smooth Roller Sliding Glass Door Track Kit (IC-SL-100)',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'Icon',
        model: 'IC-SL-100',
        unit: 'nos',
        stock: 20,
        warehouseStock: { 'Warehouse A': 15, 'Warehouse B': 5 },
        rate: 7800,
        rateUnit: 'nos',
        purchaseRate: 5600,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 4,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_ph300',
        name: 'Icon Tubular Stainless Steel D-Pull Handle (300mm)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Icon',
        model: 'IC-PH-300',
        unit: 'nos',
        stock: 70,
        warehouseStock: { 'Warehouse A': 45, 'Warehouse B': 25 },
        rate: 850,
        rateUnit: 'nos',
        purchaseRate: 580,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'handle',
        holesRequired: 2,
        cutsRequired: 0
    },
    {
        id: 'cat_icon_ph600',
        name: 'Icon H-Style Stainless Ladder Pull Handle (600mm)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Icon',
        model: 'IC-PH-600',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 1650,
        rateUnit: 'nos',
        purchaseRate: 1180,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'handle',
        holesRequired: 2,
        cutsRequired: 0
    },

    // =========================================================================
    // 4. HÄFELE / HAFELE (Startec Series, Showers, Barn Sliders)
    // =========================================================================
    {
        id: 'cat_hafele_startec_fs84',
        name: 'Häfele Startec FS 84 Architectural Floor Spring',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Hafele',
        model: 'Startec FS 84',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 5200,
        rateUnit: 'nos',
        purchaseRate: 3700,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_hafele_startec_fs75v',
        name: 'Häfele Startec FS 75V Variable Heavy Floor Spring',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Hafele',
        model: 'Startec FS 75V',
        unit: 'nos',
        stock: 25,
        warehouseStock: { 'Warehouse A': 18, 'Warehouse B': 7 },
        rate: 7200,
        rateUnit: 'nos',
        purchaseRate: 5100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_hafele_startec_pf10',
        name: 'Häfele Startec PF 10 Bottom Door Patch Fitting',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Hafele',
        model: 'Startec PF 10',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1150,
        rateUnit: 'nos',
        purchaseRate: 820,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hafele_startec_pf20',
        name: 'Häfele Startec PF 20 Top Door Patch Fitting',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Hafele',
        model: 'Startec PF 20',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 1150,
        rateUnit: 'nos',
        purchaseRate: 820,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hafele_startec_pf30',
        name: 'Häfele Startec PF 30 Overpanel Transom Pivot Patch',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Hafele',
        model: 'Startec PF 30',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 1480,
        rateUnit: 'nos',
        purchaseRate: 1050,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'overpanel_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hafele_startec_us10',
        name: 'Häfele Startec US 10 Corner Deadbolt Lock (Euro Latch)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Hafele',
        model: 'Startec US 10',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 2400,
        rateUnit: 'nos',
        purchaseRate: 1700,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hafele_98153',
        name: 'Häfele Wall-to-Glass 90° Shower Hinge (981.53.001)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Hafele',
        model: '981.53.001',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 1600,
        rateUnit: 'nos',
        purchaseRate: 1150,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_hafele_98152',
        name: 'Häfele Inline 180° Glass-to-Glass Hinge (981.52.001)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Hafele',
        model: '981.52.001',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 1950,
        rateUnit: 'nos',
        purchaseRate: 1400,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_hafele_98154',
        name: 'Häfele Corner 90° Glass-to-Glass Hinge (981.54.001)',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Hafele',
        model: '981.54.001',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 2100,
        rateUnit: 'nos',
        purchaseRate: 1500,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'glass_hinge',
        holesRequired: 4,
        cutsRequired: 2
    },
    {
        id: 'cat_hafele_slido120',
        name: 'Häfele Slido Classic 120-F Concealed Top-Hung Track',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'Hafele',
        model: 'Slido Classic 120-F',
        unit: 'nos',
        stock: 12,
        warehouseStock: { 'Warehouse A': 10, 'Warehouse B': 2 },
        rate: 14500,
        rateUnit: 'nos',
        purchaseRate: 10500,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_hafele_barn_roller',
        name: 'Häfele Exposed Stainless Steel Barn Slider Hanger Kit',
        category: 'hardware',
        type: 'Sliding Systems',
        make: 'Hafele',
        model: 'Barn Slider',
        unit: 'nos',
        stock: 15,
        warehouseStock: { 'Warehouse A': 12, 'Warehouse B': 3 },
        rate: 12800,
        rateUnit: 'nos',
        purchaseRate: 9200,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'sliding_kit',
        holesRequired: 4,
        cutsRequired: 0
    },
    {
        id: 'cat_hafele_flush_pull_50',
        name: 'Häfele Recessed Flush Ring Handle (Ø50mm)',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Hafele',
        model: 'Flush Pull Ø50mm',
        unit: 'nos',
        stock: 80,
        warehouseStock: { 'Warehouse A': 50, 'Warehouse B': 30 },
        rate: 450,
        rateUnit: 'nos',
        purchaseRate: 310,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'handle',
        holesRequired: 1,
        cutsRequired: 0
    },

    // =========================================================================
    // 5. HARDWYN, ENOX & CRL (Architectural Specialties)
    // =========================================================================
    {
        id: 'cat_hardwyn_fs84',
        name: 'Hardwyn Double Action Floor Spring HW-FS-84',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Hardwyn',
        model: 'HW-FS-84',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 3800,
        rateUnit: 'nos',
        purchaseRate: 2650,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_hardwyn_pf10',
        name: 'Hardwyn Bottom Patch Fitting HW-PF-10',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Hardwyn',
        model: 'HW-PF-10',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 850,
        rateUnit: 'nos',
        purchaseRate: 590,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hardwyn_pf20',
        name: 'Hardwyn Top Patch Fitting HW-PF-20',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Hardwyn',
        model: 'HW-PF-20',
        unit: 'nos',
        stock: 50,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 15 },
        rate: 850,
        rateUnit: 'nos',
        purchaseRate: 590,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'top_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_hardwyn_sh90',
        name: 'Hardwyn Wall-to-Glass Shower Hinge HW-SH-90',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'Hardwyn',
        model: 'HW-SH-90',
        unit: 'nos',
        stock: 60,
        warehouseStock: { 'Warehouse A': 40, 'Warehouse B': 20 },
        rate: 1250,
        rateUnit: 'nos',
        purchaseRate: 880,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_enox_ep84',
        name: 'Enox Architectural Floor Spring EP-84 (100kg)',
        category: 'hardware',
        type: 'Floor Springs',
        make: 'Enox',
        model: 'EP-84',
        unit: 'nos',
        stock: 35,
        warehouseStock: { 'Warehouse A': 25, 'Warehouse B': 10 },
        rate: 4400,
        rateUnit: 'nos',
        purchaseRate: 3100,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'floor_spring',
        holesRequired: 0,
        cutsRequired: 0
    },
    {
        id: 'cat_enox_e10',
        name: 'Enox Bottom Patch Fitting E-10',
        category: 'hardware',
        type: 'Patch Fittings',
        make: 'Enox',
        model: 'E-10',
        unit: 'nos',
        stock: 55,
        warehouseStock: { 'Warehouse A': 35, 'Warehouse B': 20 },
        rate: 920,
        rateUnit: 'nos',
        purchaseRate: 640,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'bottom_patch',
        holesRequired: 1,
        cutsRequired: 1
    },
    {
        id: 'cat_enox_indicator_lock',
        name: 'Enox Glass Partition Toilet Indicator Lock E-WC-01',
        category: 'hardware',
        type: 'Handles & Locks',
        make: 'Enox',
        model: 'E-WC-01',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 1850,
        rateUnit: 'nos',
        purchaseRate: 1300,
        purchaseRateUnit: 'nos',
        hsnCode: '83014000',
        fittingRole: 'door_lock',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_crl_geneva_sh',
        name: 'CRL Geneva Wall-to-Glass 90° Heavy Shower Hinge',
        category: 'hardware',
        type: 'Shower Hardware',
        make: 'CRL',
        model: 'Geneva GEN034',
        unit: 'nos',
        stock: 45,
        warehouseStock: { 'Warehouse A': 30, 'Warehouse B': 15 },
        rate: 2200,
        rateUnit: 'nos',
        purchaseRate: 1580,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'wall_hinge',
        holesRequired: 2,
        cutsRequired: 1
    },
    {
        id: 'cat_crl_standoff_50',
        name: 'CRL Heavy Duty Ø50mm Standoff Pin for Balustrades',
        category: 'hardware',
        type: 'Spigots & Railings',
        make: 'CRL',
        model: 'Standoff Ø50mm',
        unit: 'nos',
        stock: 100,
        warehouseStock: { 'Warehouse A': 65, 'Warehouse B': 35 },
        rate: 950,
        rateUnit: 'nos',
        purchaseRate: 650,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'spigot',
        holesRequired: 1,
        cutsRequired: 0
    },
    {
        id: 'cat_crl_4way_spider',
        name: 'CRL Heavy-Duty 4-Way Structural Spider Bracket Assembly',
        category: 'hardware',
        type: 'Spider & Facade',
        make: 'CRL',
        model: 'Heavy 4-Way Spider',
        unit: 'nos',
        stock: 30,
        warehouseStock: { 'Warehouse A': 20, 'Warehouse B': 10 },
        rate: 4600,
        rateUnit: 'nos',
        purchaseRate: 3300,
        purchaseRateUnit: 'nos',
        hsnCode: '83024110',
        fittingRole: 'connector',
        holesRequired: 4,
        cutsRequired: 0
    }
];

/**
 * Synchronizes the complete master manufacturer hardware catalog with db.items.
 * Inserts any brand items that are missing without duplicating existing products.
 */
export async function syncMasterHardwareCatalog(): Promise<{ addedCount: number; existingCount: number }> {
    try {
        const existingItems = await db.items.getAll();
        // The catalog's own ids (e.g. "cat_dorma_bts80") are only used in-memory to
        // match against HARDWARE_CUTOUT_TEMPLATES -- the `items` table's id column
        // is a real Postgres uuid, so every insert must get a fresh crypto.randomUUID()
        // instead. That means make+model (not id) is the only reliable way to tell
        // "this catalog entry was already synced" on a repeat run.
        const existingModels = new Set(
            existingItems
                .filter(i => i.category === 'hardware' && i.make && i.model)
                .map(i => `${i.make?.toLowerCase().trim()}_${i.model?.toLowerCase().trim()}`)
        );

        let addedCount = 0;
        let existingCount = 0;

        for (const catalogItem of MASTER_HARDWARE_CATALOG) {
            const modelKey = `${catalogItem.make?.toLowerCase().trim()}_${catalogItem.model?.toLowerCase().trim()}`;
            if (!existingModels.has(modelKey)) {
                await db.items.add({ ...catalogItem, id: crypto.randomUUID() });
                existingModels.add(modelKey);
                addedCount++;
            } else {
                existingCount++;
            }
        }

        return { addedCount, existingCount };
    } catch (error) {
        console.error('Failed to synchronize master hardware catalog:', error);
        throw error;
    }
}
